import {mkdir,writeFile} from 'node:fs/promises';
import {services} from './services.mjs';
import {districts} from './districts.mjs';
export const host='https://www.lomtalanitaskiurites.hu';
const phone='+36 70 803 5257', mail='lomtalanitaskiurites@gmail.com';
const pages=[];
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const link=(url,text)=>`<a href="${url}">${text}</a>`;
const p=s=>`<p>${s}</p>`;
const list=items=>`<ul class="checklist">${items.map(s=>`<li>${s}</li>`).join('')}</ul>`;
const actions=`<div class="actions"><a class="button" href="tel:+36708035257">Hívás most <span aria-hidden="true">↗</span></a><a class="text-link" href="/ajanlatkeres.html">Kérek árajánlatot <span aria-hidden="true">→</span></a></div>`;
const header=`<a class="skip" href="#tartalom">Ugrás a tartalomra</a><header class="site-header"><div class="container navigation"><a class="brand" href="/" aria-label="Lomtalanítás Kiürítés – főoldal"><span class="brand-mark" aria-hidden="true">L<span> / </span>K</span><span>LOMTALANÍTÁS<br>KIÜRÍTÉS <small>BUDAPEST</small></span></a><button class="menu-button" type="button" aria-expanded="false" aria-controls="fo-menu" hidden>Menü <span aria-hidden="true">☰</span></button><nav id="fo-menu" class="nav-links" aria-label="Fő navigáció"><a href="/#szolgaltatasok">Szolgáltatások</a><a href="/arak.html">Árak</a><a href="/keruletek/">Kerületek</a><a href="/elerhetoseg.html">Kapcsolat</a><a class="nav-phone" href="tel:+36708035257">${phone}</a></nav></div></header>`;
const footer=`<footer class="footer"><div class="container footer-grid"><div><a class="footer-brand" href="/">Több hely.<br>Kevesebb teher.</a><p>Lomtalanítás és ingatlankiürítés<br>Budapest mind a 23 kerületében.</p></div><div><h2>Elérhetőség</h2><a class="footer-phone" href="tel:+36708035257">${phone}</a><p><a href="mailto:${mail}">${mail}</a></p><a href="/ajanlatkeres.html">Ajánlatkérés fotókkal →</a></div><div><h2>Hasznos oldalak</h2><ul><li><a href="/galeria.html">Galéria</a></li><li><a href="/blog.html">Kiürítési útmutató</a></li><li><a href="/adatvedelem.html">Adatvédelem</a></li><li><button class="link-button" type="button" data-consent-settings hidden>Sütibeállítások</button></li></ul></div></div><div class="container footer-bottom"><span>Lomtalanítás / Kiürítés Budapest</span><span>Rakodás · Kihordás · Elszállítás</span></div></footer><a class="mobile-call" href="tel:+36708035257">Hívás most <span>${phone}</span></a><aside class="consent" id="cookieConsent" aria-label="Adatvédelmi beállítások" hidden><p><strong>Engedélyezi a látogatottságmérést?</strong><br>Google Analytics csak az engedélyével töltődik be. Választását megjegyezzük. <a href="/adatvedelem.html">Részletek</a></p><div><button type="button" id="rejectCookies">Csak szükséges</button><button type="button" id="acceptCookies">Mérés engedélyezése</button></div></aside><script src="/js/main.js" defer></script><script src="/cookie-popup.js" defer></script>`;
const business={'@type':'LocalBusiness','@id':host+'/#vallalkozas',name:'Lomtalanítás Kiürítés',url:host+'/',telephone:'+36708035257',email:mail,areaServed:{'@type':'City',name:'Budapest'}};
function section(kicker,title,body,{dark=false,id=''}={}){return `<section class="section${dark?' dark':''}"${id?` id="${id}"`:''}><div class="container editorial"><div class="section-label">${kicker}</div><div><h2>${title}</h2>${body}</div></div></section>`;}
function hero(title,lead,label='Budapest · Rakodás és elszállítás'){return `<section class="page-hero"><div class="container"><p class="eyebrow">${label}</p><h1>${title}</h1><p class="lead">${lead}</p>${actions}</div></section>`;}
function cta(){return `<section class="cta"><div class="container cta-inner"><div><p class="eyebrow">Kezdjük egy beszélgetéssel</p><h2>Mit kell<br>elszállítani?</h2></div><div><p>Mennyiség, helyszín, időpont.<br>A részleteket együtt pontosítjuk.</p><a class="button light" href="tel:+36708035257">${phone} <span aria-hidden="true">↗</span></a></div></div></section>`;}
function faqMarkup(faq){return section('Kérdések és válaszok','Amit érdemes előre tisztázni.',`<div class="faq">${faq.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div>`);}
function serviceLinks(slugs){return `<div class="related">${slugs.map(slug=>{const s=services.find(s=>s.slug===slug);return link('/'+slug+'/',s.name+' <span aria-hidden="true">↗</span>');}).join('')}</div>`;}
function districtLinks(ds=districts){return `<ul class="district-grid">${ds.map(d=>`<li><a href="/${d.slug}/"><strong>${d.roman}.</strong><span>${d.name==='II. kerület'||d.name==='XIII. kerület'||d.name==='XV. kerület'||d.name==='XVI. kerület'?d.areas:d.name}</span><span aria-hidden="true">↗</span></a></li>`).join('')}</ul>`;}
function process(){return section('Így dolgozunk','A felméréstől az üres helyiségig.',`<ol class="process"><li><h3>Mutassa meg a feladatot</h3><p>Telefonon átbeszéljük a helyszínt. Fotókon a teljes mennyiséget, a nagyobb tárgyakat és a kihordás útvonalát is kérjük; összetett munkánál helyszíni felmérést egyeztetünk.</p></li><li><h3>Rögzítsük a részleteket</h3><p>Egyeztetjük az elvihető tárgyakat, a díjat, a szétszerelést és az időpontot. A maradó berendezést külön jelöljük, a hozzáférést a megrendelővel pontosítjuk.</p></li><li><h3>Kihordás és elszállítás</h3><p>A megbeszélt területet kiürítjük, a kijelölt lomot felrakodjuk és elszállítjuk. A végén áttekintjük, hogy az egyeztetett tárgyak mind elkerültek-e.</p></li></ol>`);}
function pricingCopy(){return p('A végleges díj a mennyiségtől, az emelettől, a lift használhatóságától, a rakodási távolságtól és a megközelítéstől függ. A szétszerelést, a különleges tárgyakat és az esetleges többletmunkát előre egyeztetjük.')+p('A közzétett tájékoztató árlistában 1 m³ lomtalanítás 6 900 Ft, a teljes lakáskiürítés 70 000 Ft-tól szerepel. Ezek nem helyszíni felmérés nélküli, minden körülményre érvényes végösszegek.')+link('/arak.html','Árak és árképzési szempontok →');}
async function page({url,title,description,h1,body,faq=[],service=false,noindex=false,crumbParent=null}){
 if(url==='/ajanlatkeres.html')body=body.replaceAll('href="/ajanlatkeres.html"','href="#email"');
 if(service)description=crumbParent
  ? `${h1}: helyszíni előkészítés, kihordás és elszállítás. Kerületi útmutató, árképzés és fotós ajánlatkérés: ${phone}.`
  : `${h1} Budapesten. Felmérés, kihordás és elszállítás előre egyeztetett feltételekkel. Kérjen ajánlatot: ${phone}.`;
 title=title.replace(/(II\.|XIII\.|XV\.|XVI\.) kerület – \1 kerület/, '$1 kerület');
 const graph=[business,{'@type':'WebPage','@id':host+url+'#oldal',url:host+url,name:title,description,inLanguage:'hu'}];
 if(url!=='/') {const crumbs=[{name:'Főoldal',item:host+'/'}];if(crumbParent)crumbs.push({name:crumbParent.name,item:host+crumbParent.url});crumbs.push({name:h1||title,item:host+url});graph.push({'@type':'BreadcrumbList',itemListElement:crumbs.map((x,i)=>({'@type':'ListItem',position:i+1,...x}))});}
 if(service)graph.push({'@type':'Service',name:h1||title,url:host+url,provider:{'@id':host+'/#vallalkozas'},areaServed:{'@type':'City',name:'Budapest'},description});
 if(faq.length)graph.push({'@type':'FAQPage',mainEntity:faq.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))});
 const crumbs=url==='/'?'':`<nav class="breadcrumbs container" aria-label="Morzsanavigáció"><a href="/">Főoldal</a><span aria-hidden="true">/</span>${crumbParent?`<a href="${crumbParent.url}">${crumbParent.name}</a><span aria-hidden="true">/</span>`:''}<span aria-current="page">${h1||title}</span></nav>`;
 const html=`<!doctype html>
<html lang="hu">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#173b36">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(description)}">
  ${noindex?'<meta name="robots" content="noindex, follow">':''}
  <link rel="canonical" href="${host+url}">
  <link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="/css/style.css">
  <meta property="og:type" content="website">
  <meta property="og:locale" content="hu_HU">
  <meta property="og:site_name" content="Lomtalanítás / Kiürítés Budapest">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${esc(description)}">
  <meta property="og:url" content="${host+url}">
  <meta property="og:image" content="${host}/assets/lakas-lomtalanitas.webp">
  <meta property="og:image:alt" content="Világos, üres lakószoba">
  <meta name="twitter:card" content="summary_large_image">
  <script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph}).replaceAll('<','\\u003c')}</script>
</head>
<body>
${header}
<main id="tartalom">
${crumbs}
${body}
</main>
${footer}
</body>
</html>
`;
 const file=url==='/'?'index.html':url.endsWith('/')?url.slice(1)+'index.html':url.slice(1);
 if(file.includes('/'))await mkdir(file.slice(0,file.lastIndexOf('/')),{recursive:true});
 await writeFile(file,html.replace(/^[\t ]+$/gm,''));pages.push({url,file,title,noindex});
}

const homeFaq=[['Mennyibe kerül a lomtalanítás Budapesten?','A tájékoztató árlistában 1 m³ lomtalanítás 6 900 Ft. A végleges díj függ az anyag típusától, a mennyiségtől és a rakodási körülményektől. A munkát és az árat előre egyeztetjük.'],['Elég fényképet küldeni az ajánlathoz?','Áttekinthető munkánál a fotók segítenek az előzetes ajánlatban. Teljes lakás vagy nehezen hozzáférhető hely esetén helyszíni felmérés is szükséges lehet.'],['Nekem kell lehordanom a bútorokat?','A kihordást és a rakodást is egyeztetjük a szolgáltatás részeként. Nem kell a lomot előzetesen az utcára helyeznie.'],['Hétvégére is kérhetek időpontot?','Hétvégi munkáról is érdeklődhet. A konkrét időpontot a helyszín, a feladat és a szabad kapacitás alapján egyeztetjük.']];
await page({url:'/',title:'Lomtalanítás Budapest | Lakáskiürítés, rakodással',description:'Lomtalanítás Budapesten, a kihordástól az elszállításig. Lakás, hagyaték, bútor és tároló kiürítése. Fotós ajánlatkérés: +36 70 803 5257.',faq:homeFaq,body:`
<section class="home-hero"><div class="container hero-layout"><div class="hero-copy"><p class="eyebrow"><span class="status-dot" aria-hidden="true"></span> Budapest · Mind a 23 kerületben</p><h1>Lomtalanítás<br>Budapesten.<br><span>Helyet adunk<br>a következőnek.</span></h1><p class="lead">Egy régi kanapé vagy egy teljes lakás.<br>Átvállaljuk a kihordást, a rakodást és az elszállítást.</p>${actions}<p class="hero-note">Lakás · Ház · Hagyaték · Üzleti ingatlan</p></div><figure class="hero-photo"><img src="/assets/lakas-lomtalanitas.webp" width="1536" height="1024" alt="Világos, üres lakószoba parkettával és nagy ablakkal" fetchpriority="high"><figcaption><span>Egy új kezdetnek hely kell.</span><span aria-hidden="true">01 / BUDAPEST</span></figcaption></figure></div></section>
<div class="promise-strip"><div class="container"><span>Kihordással és rakodással</span><span>Előre egyeztetett díjjal</span><span>Fotós vagy helyszíni felméréssel</span></div></div>
${section('01 / Szolgáltatások','Nem csak elvisszük.<br>Kiürítjük.',p('A felesleges tárgyak eltávolítása akkor egyszerű, ha a felméréstől a rakodásig összeáll a terv. Válassza ki, milyen helyet szeretne felszabadítani.')+`<div class="service-list">${services.map((s,i)=>`<a href="/${s.slug}/"><span class="service-number">${String(i+1).padStart(2,'0')}</span><span><h3>${s.name}</h3><p>${s.lead.split('.')[0]}.</p></span><span class="arrow" aria-hidden="true">↗</span></a>`).join('')}</div>`,{id:'szolgaltatasok'})}
<section class="photo-story"><figure><img src="/assets/kep3.webp" width="1170" height="792" loading="lazy" decoding="async" alt="Elvitelre váró szekrénysor és ágy a korábbi galéria egyik szobájában"><figcaption>A korábbi galériánkból · Berendezett szoba</figcaption></figure><div><p class="eyebrow">A nehezét bízza ránk</p><h2>Ön dönt arról,<br>mi marad.</h2><p>Mi segítünk abban, hogy a többi elkerüljön. Költözés, felújítás vagy öröklés után előre tisztázzuk a kiürítés határait, a hozzáférést és az átadás részleteit.</p><a class="text-link" href="/lakaskiurites-budapest/">A lakáskiürítés menete →</a></div></section>
${process()}
${section('02 / Átlátható árképzés','A feladatra adunk árat.',`<div class="price-preview"><div><span>Lomtalanítás / 1 m³</span><strong>6 900 <small>Ft</small></strong></div><div><span>Teljes lakáskiürítés</span><strong>70 000 <small>Ft-tól</small></strong></div></div>`+p('Tájékoztató árak. A végösszeget a mennyiség, az emelet, a lift, a kihordási távolság és a szükséges szétszerelés alapján egyeztetjük.')+link('/arak.html','A teljes árlista és a részletek →'),{dark:true})}
${section('03 / Budapest','Kerületről kerületre.',p('Budán és Pesten is a helyszínhez igazítjuk a munkát. Kerületi útmutatóink segítenek összegyűjteni az ajánlathoz szükséges adatokat; nem az éves közszolgáltatási lomtalanítás időpontjait közlik.')+districtLinks())}
${faqMarkup(homeFaq)}${cta()}`});

for(const s of services){
 const faqs=[...s.faq,['Mitől függ a végleges ár?','A mennyiség, az emelet, a használható lift, a rakodási távolság, a megközelítés és a szétszerelés igénye egyaránt számít. A konkrét összeget az előre tisztázott munkára adjuk.']];
 await page({url:`/${s.slug}/`,title:s.title+' | Ajánlatkérés',h1:s.name,description:`${s.lead} Árajánlat és időpont: ${phone}.`,service:true,faq:faqs,body:hero(s.name+'<br>Budapesten.',s.lead)+section('A feladat',s.heading,p(s.intro))+section('Munkatartalom','Mit egyeztetünk az ajánlatban?',list(s.items)+p('A felmérésben rögzített feladatból indulunk ki. Ha új tárgy vagy újabb helyiség kerül a munkához, jelezze még az érkezés előtt. A különleges anyagok, bontási munkák és gépek nem automatikusan részei az általános kiürítésnek.'),{dark:true})+section('Előkészítés','Ezekkel segíthet a legtöbbet.',p(s.prep)+`<aside class="note"><strong>A maradó tárgyak legyenek egyértelműek.</strong><p>A személyes értékeket és dokumentumokat tegye külön. A kijelölt területeket a munkakezdés előtt együtt áttekintjük.</p></aside>`)+section('Egy gyakori helyzet',s.caseTitle,p(s.caseText))+process()+section('Árképzés','Mennyibe kerül a munka?',pricingCopy(),{dark:true})+section('Szolgáltatási terület','Budapest egész területén.',p('Mind a 23 kerületben egyeztethető kiürítés. A kerület neve mellett a pontos megközelítés is fontos: emeleti lakás, belső udvar, lépcsős telek vagy szűk tároló esetén eltérhet a rakodás munkaigénye.')+link('/keruletek/','Kerületi útmutatók és előkészítés →'))+faqMarkup(faqs)+section('Kapcsolódó feladatok','Ami még szóba kerülhet.',serviceLinks(s.related))+cta()});
}

await page({url:'/keruletek/',title:'Lomtalanítás Budapest 23 kerületében | Helyi útmutatók',h1:'Budapesti kerületek',description:'Lomtalanítás Budán és Pesten: 23 kerületi útmutató a kihordás, a lift, a megközelítés és az ajánlatkérés előkészítéséhez.',body:hero('Budapest.<br>Mind a 23 kerület.', 'A jó ajánlathoz nem csak a címet kérjük. Válassza ki a kerületet, és nézze át, mire érdemes felkészülni az adott helyszínen.')+section('Helyi útmutatók','Hol kell felszabadítani a helyet?',districtLinks())+section('Időpont-egyeztetés','Saját megrendelés, saját feladat.',p('Kerületi oldalaink az egyedileg megrendelhető, fizetős lomtalanításról szólnak. Nem közszolgáltatási időpontnaptárak. A munka napját a feladat és a szabad kapacitás alapján beszéljük meg.')+serviceLinks(['lomtalanitas-budapest','lakaskiurites-budapest']))+cta()});

for(const d of districts){const s=services.find(s=>s.slug===d.service);const faq=[[d.question,d.answer],['Milyen adatokat küldjek az ajánlatkéréshez?',`A ${d.roman}. kerületi helyszín mellett adja meg az emeletet, a lift használhatóságát, a tárgyak listáját és a rakodóhely távolságát. A teljes mennyiségről és a kihordás útvonaláról is küldjön fotókat.`],['Mikorra kérhető a kiürítés?','A konkrét napot telefonon egyeztetjük. Ha ingatlanátadáshoz vagy más szállító érkezéséhez kell igazodni, ezt az első beszélgetéskor jelezze.']];
 await page({url:`/${d.slug}/`,title:`Lomtalanítás ${d.roman}. kerület – ${d.name} | Budapest`,h1:`Lomtalanítás ${d.roman}. kerület`,description:`Lomtalanítás és kiürítés a ${d.roman}. kerületben. ${d.heading}. Fotós felmérés, kihordás és előre egyeztetett ár: ${phone}.`,service:true,faq,crumbParent:{name:'Kerületek',url:'/keruletek/'},body:hero(`Lomtalanítás<br>${d.roman}. kerület.`,`${d.name} – kiürítés és elszállítás a helyszínhez igazítva. A nagyobb bútorok mellett a kisebb holmik és a rakodási útvonal is része a felmérésnek.`,d.areas)+section('A helyszín előkészítése',d.heading+'.',p(d.intro)+p('Az alábbi szempontok az egyeztetést segítik. A konkrét ház adottságait mindig külön ellenőrizzük; helyi behajtási vagy parkolási engedély meglétét nem feltételezzük.'))+section('Az ajánlat előtt','Erre készüljön ennél a helyszínnél.',list(d.checklist),{dark:true})+section('A feladathoz igazítva',s.name+' és kapcsolódó munkák.',p(s.intro)+p(s.prep)+serviceLinks([d.service,'lomtalanitas-budapest',d.service==='butor-elszallitas'?'lakaskiurites-budapest':'butor-elszallitas']))+section('Egyeztetett munkafolyamat','A hozzáféréstől az átadásig.',`<ol class="process"><li><h3>Helyszín és mennyiség</h3><p>Küldje el a fenti ellenőrzőlista adatait és a fotókat. Jelezze a kapukód vagy kulcs elérhetőségét, de ezeket ne tegye a nyilvánosan megosztott képekre.</p></li><li><h3>Ár és időpont</h3><p>A kiürítésre kijelölt tárgyakról és a kihordási útvonalról egyeztetünk. A házban érvényes munkavégzési idősávot a megrendelővel pontosítjuk.</p></li><li><h3>Rakodás és ellenőrzés</h3><p>Az egyeztetett tárgyakat kivisszük és elszállítjuk. A befejezéskor az előzetesen kijelölt munkaterületet tekintjük át.</p></li></ol>`)+section('Árképzés','A kerület önmagában nem határozza meg az árat.',pricingCopy(),{dark:true})+faqMarkup(faq)+section('További helyszínek','Másik kerületben is van feladat?',p('Ha több ingatlan kiürítését tervezi, minden címet külön jelezzen. Ezek a közeli vagy kapcsolódó budapesti területek útmutatói:')+districtLinks(d.near.map(n=>districts[n-1]))+p(link('/','Lomtalanítás Budapest – főoldal →')+' · '+link('/keruletek/','Összes kerület →')))+cta()});
}

const prices=[['Lomtalanítás, 1 m³','6 900 Ft'],['Bútor elszállítás, 1 darab','5 000 Ft-tól'],['Szekrénysor elszállítás','25 000 Ft-tól'],['Mosógép elszállítás','8 000 Ft-tól'],['Hűtő elszállítás','12 000 Ft-tól'],['Kanapé elszállítás','20 000 Ft-tól'],['Franciaágy elszállítás','15 000 Ft-tól'],['Teljes lakáskiürítés','70 000 Ft-tól']];
const priceFaq=[['A köbméterárból kiszámolható a végösszeg?','Önmagában nem mindig. A lom típusa, a kihordás, az emelet, a lift és a szétszerelés is befolyásolja az ajánlatot.'],['Mit jelent a „Ft-tól” ár?','Induló, tájékoztató összeget. A konkrét munkára érvényes végösszeget az előzetes egyeztetés során pontosítjuk.'],['Milyen járulékos költségekről kérdezzek?','Tisztázzuk a kihordást, a szétszerelést, a megközelítést, a különleges tárgyakat és az esetleges többletmunkát, valamint a fizetendő végösszeget és annak adótartalmát.']];
await page({url:'/arak.html',title:'Lomtalanítás árak és lakáskiürítés árak | Budapest',h1:'Lomtalanítás és lakáskiürítés árak',description:'Lomtalanítás 6 900 Ft/m³, teljes lakáskiürítés 70 000 Ft-tól a tájékoztató árlistában. Árat befolyásoló tényezők és egyedi ajánlat Budapesten.',faq:priceFaq,body:hero('Árak. Előre<br>átbeszélve.','Tájékoztató díjak az első tervezéshez. A végleges árat a tényleges feladatra és a rakodási körülményekre egyeztetjük.','Lomtalanítás és lakáskiürítés árak')+section('Tájékoztató árlista','Mennyibe kerülhet?',`<table class="price-table"><caption>Lomtalanítás és kiürítés tájékoztató díjai</caption><thead><tr><th scope="col">Szolgáltatás</th><th scope="col">Tájékoztató ár</th></tr></thead><tbody>${prices.map(([a,b])=>`<tr><th scope="row">${a}</th><td>${b}</td></tr>`).join('')}</tbody></table><p class="small">A tételek nem adódnak automatikusan össze. A pontos munkatartalmat, a fizetendő végösszeget, annak adótartalmát és az esetleges további költségeket ajánlatkéréskor tisztázzuk.</p>`)+section('Mi befolyásolja?','Nem csak a köbméter számít.',`<dl class="factors"><dt>Mennyiség és összetétel</dt><dd>A bútorok mellett a dobozok, zsákok, tárolók tartalma és az anyagfajták is számítanak.</dd><dt>Emelet és lift</dt><dd>A használható lift mérete, a lépcsőfordulók és a kézi kihordás szakaszai befolyásolják a munkát.</dd><dt>Rakodási távolság</dt><dd>A lakás, a kapu és a jármű közötti távolságot, a parkolást és a megközelítést is fel kell mérni.</dd><dt>Szétszerelés és különleges tárgyak</dt><dd>Beépített bútor, nagy súlyú tárgy vagy bekötött gép esetén külön egyeztetés szükséges.</dd></dl>`,{dark:true})+section('Lakáskiürítés árak','Teljes lakásnál helyiségenként mérünk.',p('A 70 000 Ft-tól induló tájékoztató összeg nem négyzetméter-alapú tarifa. A berendezés sűrűsége, a tárolók tartalma és a kihordás befolyásolja a munkát. Üres szekrény és könyvekkel, ruhákkal teli szekrénysor más mennyiséget jelent.')+p('Küldjön áttekintő képet minden érintett helyiségről. A pincét és a garázst is vegye bele, ha azokat szintén ki kell üríteni.')+link('/lakaskiurites-budapest/','A lakáskiürítés részletei →'))+faqMarkup(priceFaq)+cta()});

const quoteBody=hero('Mutassa meg,<br>mit kell elvinni.','Néhány áttekintő fotó és a helyszín adatai segítenek az előzetes ajánlatban. Összetettebb munkához helyszíni felmérést is egyeztethetünk.','Ajánlatkérés fotók alapján')+section('Fotók és alapadatok','Ezeket küldje el nekünk.',list(['Kép minden érintett helyiségről és a nagyobb tárgyakról.','Kerület, emelet, lift és a rakodási pont távolsága.','Mi marad, mi vihető el, szükséges-e szétszerelés.','Kívánt időpont, elérhetőség és különleges körülmények.'])+p('A fényképeken ne látszódjon személyes irat, bankszámlaadat vagy más bizalmas információ. A képeket közvetlenül az e-mailhez csatolhatja.'))+section('Írjon nekünk','Fotós ajánlatkérés e-mailben.',`<p><a class="contact-mail" href="mailto:${mail}?subject=Lomtalan%C3%ADt%C3%A1s%20%E2%80%93%20fot%C3%B3s%20aj%C3%A1nlatk%C3%A9r%C3%A9s">${mail}</a></p><p>Az alábbi segéd kitölti az e-mail tárgyát és szövegét. Az üzenetet a saját levelezőjében ellenőrizheti, ott csatolhat fotókat, majd Ön küldi el.</p><form id="quote-form" hidden><div class="form-grid"><label>Név <input name="name" autocomplete="name" required maxlength="100"></label><label>Telefon vagy e-mail <input name="contact" autocomplete="email" required maxlength="150"></label><label>Kerület és emelet <input name="location" placeholder="Pl. XI. kerület, 3. emelet" required maxlength="150"></label><label>Lift, megközelítés <input name="access" placeholder="Pl. van lift, a kaputól 30 méter" maxlength="250"></label></div><label>Mit kell elszállítani?<textarea name="message" rows="5" required maxlength="3000" placeholder="Tárgyak, mennyiség, maradó berendezés, kívánt időpont"></textarea></label><p class="small">Az adatok az e-mail megnyitásáig a böngészőben maradnak. Adatkezelés: <a href="/adatvedelem.html">tájékoztató</a>.</p><button class="button" type="submit">E-mail összeállítása <span aria-hidden="true">↗</span></button><p id="quote-status" role="status"></p><div id="quote-fallback" hidden><p>Ha nem nyílt meg a levelezője, másolja ki az alábbi szöveget és küldje a fenti címre. A fotókat csatolja az üzenethez.</p><label>Másolható ajánlatkérő szöveg<textarea id="quote-copy" rows="8" readonly></textarea></label></div></form><noscript><p>Az összeállító JavaScriptet használ. Ajánlatkéréshez írjon közvetlenül a fenti e-mail-címre, vagy hívjon minket.</p></noscript>`,{id:'email'})+cta();
await page({url:'/ajanlatkeres.html',title:'Ajánlatkérés fotókkal | Lomtalanítás Budapest',h1:'Ajánlatkérés',description:'Küldje el, mit kell elszállítani: fotók, kerület, emelet és megközelítés alapján egyeztetünk. Telefonos ajánlatkérés: +36 70 803 5257.',body:quoteBody});
await page({url:'/elerhetoseg.html',title:'Kapcsolat | Lomtalanítás Kiürítés Budapest',h1:'Kapcsolat',description:'Lomtalanítás és lakáskiürítés egyeztetése Budapesten. Telefon: +36 70 803 5257. Fotók küldése: lomtalanitaskiurites@gmail.com.',body:hero('Beszéljük meg<br>a részleteket.','Mondja el, mit és honnan kell elszállítani. A mennyiséget, a hozzáférést és a kívánt időpontot együtt pontosítjuk.','Kapcsolat')+section('Elérhetőségeink','Telefonon vagy fotókkal.',`<p class="contact-phone"><a href="tel:+36708035257">${phone}</a></p><p><a class="contact-mail" href="mailto:${mail}">${mail}</a></p><p>Hétvégi időpontról is érdeklődhet. Az érkezést mindig előzetes egyeztetés alapján tervezzük; állandó ügyfélfogadó irodacímet itt nem tüntetünk fel.</p><a class="text-link" href="/ajanlatkeres.html">Fotós ajánlatkérés lépései →</a>`)+section('A beszélgetés előtt','Négy adat, amivel gyorsabban haladunk.',list(['Milyen tárgyakat kell elvinni, és körülbelül mennyit?','Melyik kerületből, milyen emeletről és használható-e lift?','Milyen messze lehet a kaputól rakodni?','Van-e átadási határidő vagy előre egyeztetett időpont?']))+section('Budapest','Itt dolgozunk.',p('Lomtalanítást és kiürítést Budapest mind a 23 kerületében egyeztethet velünk. A pontos munkakörülményeket minden címen külön mérjük fel.')+link('/keruletek/','Kerületi útmutatók →'))});

await page({url:'/galeria.html',title:'Galéria | Lakáskiürítés és lomtalanítás',h1:'Galéria',description:'Képek a korábbi weboldal galériájából: berendezett és kiürített szoba. Lakáskiürítés előkészítése és fotós ajánlatkérés Budapesten.',body:hero('A tárgyak mögött<br>ott a tér.','A korábbi oldalunk galériájából megőrzött felvételek. Minden kiürítés terjedelmét a helyszín és az elvitelre kijelölt tárgyak alapján beszéljük meg.','Galéria')+`<section class="section"><div class="container gallery"><figure><img src="/assets/kep3.webp" width="1170" height="792" loading="lazy" decoding="async" alt="Berendezett szoba szekrénysorral és ággyal"><figcaption>Berendezett szoba · A korábbi galériából</figcaption></figure><figure><img src="/assets/kiuritott-szoba.webp" width="1440" height="1080" loading="lazy" decoding="async" alt="Kiürített szoba, látható parkettával és ablakkal"><figcaption>Kiürített szoba · A korábbi galériából</figcaption></figure></div></section>`+section('Fotós felmérés','Mit mutasson meg az ajánlathoz?',p('Egy távoli kép segít áttekinteni a helyiséget, a közeli felvételek pedig a nagyobb tárgyakat mutatják meg. A kihordás útvonalát, a liftet és a lépcsőfordulót is fotózza le. Nem szükséges műtermi minőség: a teljes mennyiség és a megközelítés legyen látható.')+link('/ajanlatkeres.html','Küldje el, mit kell elszállítani →'))+cta()});

const articles=[
 ['ingyenes-lomtalanitas','Lehet ingyenes a lomtalanítás?', 'A használható tárgyaknak lehet új gazdája, de a kiürítés költségét ez nem minden esetben fedezi.',p('Érdemes különválasztani a megőrizhető, továbbadható és már használhatatlan holmikat. Egy jó állapotú bútor értékét nem csak a kora vagy eredeti ára határozza meg: az állapot, a kereslet és az elszállítás is számít. A továbbadás megszervezése időt igényelhet, ezért szoros átadási határidőnél erre is hagyjon tartalékot.')+p('Értékbeszámításról csak a konkrét tárgyak ismeretében lehet beszélni. Fotón mutassa meg a sérüléseket és a teljes bútort. A megrendelt kiürítés díját és az esetleges beszámítást külön kell tisztázni; ne számítson automatikusan költségmentes munkára.')+p('A közszolgáltatási lomtalanítás aktuális lehetőségeit és feltételeit a <a href="https://www.mohubudapest.hu/">MOHU Budapest hivatalos oldalán</a> ellenőrizze. Ez különbözik az itt megrendelhető, saját időpontban végzett szolgáltatástól.')+link('/hagyatek-felszamolas/','Hagyatéki ingóságok kiürítése →')],
 ['lemaradt-lomtalanitas','Ha nem tud várni az éves lomtalanításra', 'Költözés vagy ingatlanátadás esetén a saját határidőből érdemes kiindulni.',p('Először készítsen tárgylistát: mi vihető tovább az új lakásba, mi adható át másnak, és mi az, ami már felesleges. Az elvihető tárgyak mennyiségét a csomagokkal együtt becsülje meg. Ha csak egy bútort cserél le, arra külön is lehet ajánlatot kérni.')+p('A választott időpontban megrendelt lomtalanításnál a kihordás és a rakodás feltételei is egyeztethetők. A szabad kapacitásról érdeklődjön előre; az aznapi érkezést nem érdemes biztosra venni. Jelezze, ha kulcsátadáshoz vagy új bútor szállításához kell igazodni.')+p('Ne készítse ki a tárgyakat előzetes egyeztetés nélkül a ház elé. Fotózza le a helyükön, és tisztázzuk, hogy honnan történik a kihordás.')+link('/lomtalanitas-budapest/','Lomtalanítás rakodással →')],
 ['lakaskiurites-menete','Lakáskiürítés lépésről lépésre', 'A jó előkészítés a maradó tárgyak kijelölésével kezdődik.',p('Járja végig a szobákat, konyhát, fürdőt és tárolókat. Tegye félre a dokumentumokat, kulcsokat, fényképeket és személyes emlékeket. A maradó bútorokat jelölje meg, és ellenőrizze, hogy a szekrényekben nem maradt-e megőrzendő holmi. Örökölt lakásnál az érintettek döntéseit még munkakezdés előtt érdemes egyeztetni.')+p('Ezután készülhet a mennyiségi és hozzáférési felmérés. A lift, az emelet, a lépcső és a parkolási pont távolsága ugyanúgy számít, mint a bútorok darabszáma. Beépített szekrényről vagy bekötött gépről külön beszéljünk, mert a leválasztás nem egyszerű bútormozgatás.')+p('A kiürítés végén nézze át a kijelölt helyiségeket. A nagytakarítás, fertőtlenítés vagy bontás nem automatikusan része a lomtalanításnak: ha szükséges, ezeket az ajánlat előtt külön kell tisztázni.')+link('/lakaskiurites-budapest/','Teljes és részleges lakáskiürítés →')],
 ['butor-elokeszitese','Bútor elszállítása: mit készítsen elő?', 'A méret és a kihordási útvonal együtt dönti el, hogyan mozgatható a tárgy.',p('Ürítse ki a fiókokat, szekrényeket és az ágyneműtartót. A külön szállítandó tárgyakat tegye kezelhető dobozokba; ne töltse túl őket nehéz könyvekkel. Jelezze a tükröt, az üveget, az éles részeket és a beépített elektromos szerkezetet.')+p('Mérje meg a nagyobb elemeket, az ajtónyílást és a liftet, ha az útvonal szűknek tűnik. A fordulókról készült kép sokat segít. A falhoz rögzített vagy nagy súlyú bútor bontásába ne kezdjen úgy, hogy annak mozgatása nincs megtervezve.')+p('Új bútor érkezésekor hagyjon időt a két fuvar között. A régi tárgy elszállítását és az új szállító érkezését külön kell egyeztetni, hogy a bejárat és a rakodóhely használható maradjon.')+link('/butor-elszallitas/','Bútorelszállítás részletei →')]
];
await page({url:'/blog.html',title:'Lomtalanítási és lakáskiürítési útmutató | Blog',h1:'Kiürítési útmutató',description:'Gyakorlati segítség lomtalanításhoz: értékbeszámítás, éves lomtalanítás alternatívái, lakáskiürítés menete és bútorok előkészítése.',body:hero('Kevesebb kérdés.<br>Átgondoltabb kiürítés.','Gyakorlati útmutatók az első válogatástól a bútorok elszállításáig.','Útmutató / Blog')+section('Tartalom','Amiről érdemes előre olvasni.',`<ul class="article-index">${articles.map(([id,title])=>`<li>${link('#'+id,title+' →')}</li>`).join('')}</ul>`)+articles.map(([id,title,intro,body])=>`<article id="${id}" class="section article"><div class="container editorial"><div class="section-label">Kiürítési útmutató</div><div><h2>${title}</h2><p class="article-lead">${intro}</p>${body}</div></div></article>`).join('')+cta()});

await page({url:'/adatvedelem.html',title:'Adatvédelmi tájékoztató | Lomtalanítás Kiürítés',h1:'Adatvédelmi tájékoztató',description:'Kapcsolatfelvétel, fotós ajánlatkérés és a választható Google Analytics mérés adatkezelési információi, valamint sütibeállítások.',body:hero('Adatvédelmi<br>tájékoztató.','A kapcsolatfelvétel és a weboldal használata során megadott adatok kezeléséről.','Adatvédelem')+section('01','Kapcsolattartás és adatkezelő.',p('Adatkezelő: Putnoki Sarolta e.v.')+p(`Adatkezelési kérdés vagy kérelem: <a href="mailto:${mail}">${mail}</a>, telefon: <a href="tel:+36708035257">${phone}</a>.`))+section('02','Ajánlatkérés és fényképek.',p('Telefonos vagy e-mailes kapcsolatfelvételnél az Ön által megadott nevet, elérhetőséget, helyszínadatokat, üzenetet és csatolt képeket az ajánlatkérés megválaszolásához és a munka egyeztetéséhez használjuk. Az ajánlatkérés során megadott adatok kezelése a kérésére történő, szerződéskötést megelőző egyeztetést szolgálja.')+p('Az oldali ajánlatkérő segéd a böngészőben állítja össze az üzenetet. A kitöltött adatokat nem küldi külön űrlapszolgáltatónak; az e-mailt a saját levelezőjében Ön küldi el. A fogadó e-mail-cím Gmail-fiók, ezért az üzenetet a levelezési szolgáltató is feldolgozza. Képein ne szerepeljen szükségtelen személyes adat vagy bizalmas irat.'))+section('03','Látogatottságmérés és helyi tárolás.',p('A Google Analytics mérőkódja csak akkor töltődik be, ha a „Mérés engedélyezése” lehetőséget választja. A mért adatok között oldallátogatási és eszközadatok szerepelhetnek. Hirdetési célú tárolást és személyre szabást ez a beállítás nem engedélyez.')+p('A választást a böngésző helyi tárolója legfeljebb 180 napig őrzi (lk-consent-v1). Ha nem engedélyezi a mérést, a telefonos és e-mailes kapcsolatfelvétel továbbra is használható. A korábbi általános elfogadást nem tekintjük az új mérés engedélyezésének.')+p('A hozzájárulás a lábléc Sütibeállítások gombjával módosítható. Visszavonáskor a mérés leáll, a hozzáférhető Analytics-sütik törlését megkíséreljük, az oldal újratöltődik. Ez a korábban már továbbított adatok törlését önmagában nem jelenti.')+p('A Google szolgáltatásairól: <a href="https://policies.google.com/privacy?hl=hu">Google adatvédelmi irányelvek</a>.'))+section('04','Megőrzés és kérelmek.',p('A megadott adatokat az egyeztetés és az esetleges megrendelés teljesítéséhez szükséges ideig kezeljük; a kötelező megőrzés alá tartozó bizonylatokra eltérő szabályok vonatkozhatnak. Az adott megkeresés adatairól és megőrzéséről e-mailben kérhet részletes tájékoztatást.')+p('Kérhet hozzáférést az Önre vonatkozó adatokhoz, helyesbítést, törlést vagy a kezelés korlátozását, továbbá az alkalmazható feltételek mellett tiltakozhat és kérheti az adatok hordozhatóságát. A mérési hozzájárulás visszavonható. Adatvédelmi panasszal a <a href="https://www.naih.hu/">Nemzeti Adatvédelmi és Információszabadság Hatósághoz</a> is fordulhat.'))});
await page({url:'/404.html',title:'Az oldal nem található | Lomtalanítás Kiürítés',h1:'Az oldal nem található',description:'A keresett oldal nem található. Válasszon szolgáltatást vagy keressen minket telefonon.',noindex:true,body:hero('Ez az oldal<br>nem található.','Lehet, hogy a cím elgépelés miatt nem nyílt meg. A főoldalról minden szolgáltatást és kerületi útmutatót elér.','404')+section('Merre tovább?','Segítünk megtalálni.',p(link('/','Vissza a főoldalra →'))+serviceLinks(['lomtalanitas-budapest','lakaskiurites-budapest'])+p(link('/arak.html','Árlista →')))});

await writeFile('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${pages.filter(p=>!p.noindex).map(p=>`  <url><loc>${host+p.url}</loc></url>`).join('\n')}\n</urlset>\n`);
await writeFile('robots.txt',`User-agent: *\nAllow: /\n\nSitemap: ${host}/sitemap.xml\n`);
await writeFile('tools/pages.json',JSON.stringify(pages,null,2)+'\n');
console.log(`Built ${pages.length} static pages, ${pages.filter(p=>!p.noindex).length} sitemap URLs.`);
